name: main

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次，可以根据需要调整时间
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python itv.py

    - name: Commit and push changes
      run: |
        git config --local user.name "cx-bot100"
        git config --local user.email ""
        git add itv.txt
        git commit -m "Update itv.txt with latest scrape data"
        git push
