name: zb

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 selenium webdriver-manager

      - name: Run Python script
        run: python zby.py  # 确保脚本名与此处一致

      - name: Commit and push changes
        run: |
          git config --global user.name 'cx-bot100'
          git config --global user.email 'actions@github.com'
          git add zblink.txt
          git commit -m "Update zblink.txt with latest validated IPs"
          git push
