name: ip

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Python script
        run: python ips.py  # 确保脚本名与此处一致

      - name: Commit and push changes
        run: |
          git config --global user.name 'cx-bot100'
          git config --global user.email ''
          git add ips.txt
          git commit -m "Update ips.txt with latest extracted content"
          git push
